version: "3"

services:
  web:
    build: .
    image: moneio_backend:latest
    ports:
      - 8080:8080
    volumes:
      - image-volume:/go/src/github.com/hermesespinola/moneio/images

volumes:
  image-volume: {}
